/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LibMath */

#ifndef _Included_LibMath
#define _Included_LibMath
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     LibMath
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_LibMath_add
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
